# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# test

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        r-version: ['3.6.3', '4.1.1']

    steps:
    - uses: actions/checkout@v3
    - name: Set up R ${{ matrix.r-version }}
      uses: uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}